### ISSUE TITLE
参数设置里调整repeatable这一项没有效果

### ISSUE THREAD

**Issue by iicanfly** [JingsenZhang/Recbole-Debias#1]
使用的模型是DICE，验证方式采用了leave one out的方式，repeatable = True 和 repeatable = False的结果是一样的，想问一下目前是否还没有repeatable这一功能？

**Comment by JingsenZhang** [comment]
你好，谢谢提问。请问参数repeatable是哪里的?  我好像没有发现DICE有这个参数

**Comment by JingsenZhang** [comment]
update
