### ISSUE TITLE
AttributeError: Metric 'custommetric' has no attribute [metric_need].

### ISSUE THREAD

**Issue by Tokkiu** [JingsenZhang/Recbole-Debias#12]
![Screenshot 2023-03-07 at 11 54 24 AM](https://user-images.githubusercontent.com/13414571/223316707-afbec2e0-de70-4621-bf51-dbcda01fd368.png)

Hi, thank you for your work. Now I tried to run your project in a new conda env. I installed the latest recbole. But the error occurs. Do I need to correct any recbole versions?

**Comment by JingsenZhang** [comment]
It is recommended to try the version 1.0.1

**Comment by Tokkiu** [comment]
Thanks for your quick reply.

![Screenshot 2023-03-07 at 2 00 51 PM](https://user-images.githubusercontent.com/13414571/223333903-2e34927e-f970-4b67-ae04-edc8dba37ada.png)
However, when I set the recbole as 1.0.1. The error occures.

**Comment by Tokkiu** [comment]
The content of error msg is as follows.

Traceback (most recent call last):
  File "run_recbole_debias.py", line 7, in <module>
    from recbole_debias.quick_start import run_recbole_debias
  File "/Users/Ary/dev/lab/Recbole-Debias/recbole_debias/quick_start/__init__.py", line 1, in <module>
    from recbole_debias.quick_start.quick_start import *
  File "/Users/Ary/dev/lab/Recbole-Debias/recbole_debias/quick_start/quick_start.py", line 9, in <module>
    from recbole.data import construct_transform
ImportError: cannot import name 'construct_transform' from 'recbole.data' (/Users/Ary/anaconda3/envs/bias/lib/python3.8/site-packages/recbole/data/__init__.py)

**Comment by dain5832** [comment]
I also faced the same issue and solve by adding these two lines.
"/PATHTOANACONDA/anaconda3/envs/lightgcl/lib/python3.9/site-packages/recbole/evaluator/register.py"
<img width="646" alt="image" src="https://github.com/JingsenZhang/Recbole-Debias/assets/62231006/1312940f-b931-4275-933d-b877de8363b3">

**Comment by JingsenZhang** [comment]
Thanks for your contribution, I'll fix it soon.

**Comment by Baxkiller** [comment]
> I also faced the same issue and solve by adding these two lines. "/PATHTOANACONDA/anaconda3/envs/lightgcl/lib/python3.9/site-packages/recbole/evaluator/register.py" <img alt="image" width="646" src="https://user-images.githubusercontent.com/62231006/244245252-1312940f-b931-4275-933d-b877de8363b3.png">

Hello, @dain5832 . I follow the code change in the figure you provided and it works. But i want to know does this change safe and will not change the correctness of the project? Do you meet any problem in the future usage of this project with the code change?
Looking forward to your reply. Thank you.
