### ISSUE TITLE
Question regarding how to build uniform test set

### ISSUE THREAD

**Issue by dain5832** [JingsenZhang/Recbole-Debias#13]
In many debiasing papers (DICE, MACR) it is mentioned that the test set was created by sampling items uniformly.
Can you tell me what part of the config file I need to modify if I want to sample the test set in the following way?
It seems like you only have 'train_neg_sample_args' in your DICE config file, which is about sampling the negatives during the training process, not the test data.

**Comment by JingsenZhang** [comment]
Thank you for your interest in the project.
Our toolkit does not involve the production of test set data. This part is prepared in advance, and the method is to sample based on the popularity of items.
