### ISSUE TITLE
Unable to use this package

### ISSUE THREAD

**Issue by yueqingliang1** [JingsenZhang/Recbole-Debias#14]
I use the code provided by Recbole's official website: 

`from recbole_debias.quick_start import run_recbole_debias`
`run_recbole_debias(model='PDA', dataset='ml-100k')`

However, I got the following error: 

> AttributeError: Metric 'custommetric' has no attribute [metric_need].

How can I use this package?

**Comment by Baxkiller** [comment]
#12 
This may could solve the problem
