### ISSUE TITLE
Worse performance of MF_IPS than MF on `ml` dataset.

### ISSUE THREAD

**Issue by Baxkiller** [JingsenZhang/Recbole-Debias#15]
Hello, first of all, thank you to your team for developing rebole.

During the process of using rebole-debias, I followed your config in the [Details](https://github.com/JingsenZhang/Recbole-Debias/blob/master/details/ml.md) and downloaded the data you provided in [Here](https://drive.google.com/drive/folders/1W6fvJN9ZjuyeqsIuUeodDJk_ajajHkoG).

I ran the `MF` model and `MF_IPS` model separately on this dataset with corresponding configurations. But The `MF_IPS` model shows worse than `MF`.

May I ask if this is a normal phenomenon? If not, how can I get better performace of MF_IPS model than MF model?

Looking forward to your reply.
Thanks.

**Comment by JingsenZhang** [comment]
Thank you for your attention to the project.
I think it is reasonable. The improvement of MF_IPS is to use the estimated IPS to reweight the samples. However, the IPS calculated by heuristic methods (e.g., based on item popularity) can be inaccurate, so more complex methods are used in many efforts to correct bias (e.g., learn-based methods, doubly robust methods, etc.).
