### ISSUE TITLE
CausE模型的yaml文件中缺少必要的参数：self.intervene_mask_field = config['INTERVENE_MASK']         self.LABEL = config['LABEL_FIELD']

### ISSUE THREAD

**Issue by MountainShan214** [JingsenZhang/Recbole-Debias#17]

**Comment by JingsenZhang** [comment]
Thank you for your attention to our project. Please read the project documentation carefully before use.
[Details](https://github.com/JingsenZhang/Recbole-Debias/tree/master/details)

You should set these parameters in dataset's config files.
INTERVENE_MASK: intervene_mask
LABEL_FIELD: label
