### ISSUE TITLE
Unable to start run_recbole_debias.py

### ISSUE THREAD

**Issue by lfadljevic** [JingsenZhang/Recbole-Debias#18]
Dear maintainers,

I tried to simply run the starting script as described at the beginning of the README.md file (e.g., <code>python run_recbole_debias.py
</code>) and I got the following error immediately:

<code>AttributeError: Metric 'custommetric' has no attribute [metric_need]</code>

I have successfully installed all the requirements within my virtual environment and without any changes in existing code I am not able to run the script. I also tried to add the missing parser argument "metric_need" in the main method of the run_recbole_debias.py script as follows, but it didn't work:

<code>parser.add_argument('--metric_need', '-mn', type=str, default='rec.items', help='config files')</code>

Am I missing some crucial part of the run command or do I need to something else? 
I am kindly asking you for your support.

**Comment by JingsenZhang** [comment]
Thank you for your interest in the project.
And this https://github.com/JingsenZhang/Recbole-Debias/issues/12 may could solve the problem.
