### ISSUE TITLE
直接运行项目 报错

### ISSUE THREAD

**Issue by lsy2021-07** [JingsenZhang/Recbole-Debias#2]
ValueError: Usecols do not match columns, columns expected but not found: ['user_id:token', 'timestamp:float', 'rating:float', 'item_id:token']

**Comment by JingsenZhang** [comment]
Hi,
I tried once again, and it can be run directly.
Please provide more details of running.
Thanks.

**Comment by JingsenZhang** [comment]
你好，
我刚刚试过了，是可以跑通的。
得设置好config文件，对于不同的数据集来说，要把数据集中的字段对应上才可以。
字段信息请学习recbole文档。https://recbole.io/docs/index.html

**Comment by JingsenZhang** [comment]
recbole version>=1.0.1

**Comment by ChenglongMa** [comment]
这里有两种解决办法：
1. 将 [recbole/properties/dataset](https://github.com/RUCAIBox/RecBole/tree/master/recbole/properties/dataset) 复制到 [recbole_debias/properties](https://github.com/JingsenZhang/Recbole-Debias/tree/master/recbole_debias/properties) 下；
2. 按照提交的pull request https://github.com/JingsenZhang/Recbole-Debias/pull/7 修改代码

希望有所帮助，谢谢！
